### ISSUE TITLE
suggest: manage code examples and text together

### ISSUE THREAD

**Issue by Seasawher** [lecopivo/scientific-computing-lean#2]
Hi. Thank you for developing the excellent library. I look forward to the completion of the book.

I have seen the structure of the book, but with this structure, don't you have to manage the code examples and the text separately?

What about generating markdown files from Lean files with a tool and turning them into a book in mdbook? This is similar to the way adopted in the [metaprogramming book](https://github.com/leanprover-community/lean4-metaprogramming-book).

**Comment by lecopivo** [comment]
Also I'm wondering what is the progress with Verso and if I should wait for it or adopt the existing mdbook workflow l
